version: "3.9"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: "mongodb://mongo:27017/taskdb" # conexión interna al contenedor mongo

volumes:
  mongo-data:
