version: "3.9"

services:
  db:
    image: mysql
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ejer2db
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
  app:
    build: .
    depends_on:
      - db
    links: 
      - db
    ports:
      - 3000:3000

volumes:
  mysql_data:


